### ISSUE TITLE
14 -- Express Yourself -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#205]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by BobAmand** [comment]
https://github.com/BobAmand/express-yourself
@powder-river   @jamesmallen 

Could only get 2 tests to pass.

**Comment by powder-river** [comment]
@jamesmallen @BobAmand good review together this morning. Like I said if I were you I would just revisit this assignment here and there to better understand regex. Also don't forget that sliming a test can sometimes be a useful approach. It can allow us to see vulnerabilities in order to write better code!
