### ISSUE TITLE
01--Fly Your Flag -- Kathleen Rauh

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#30]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [ ] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [ ] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [ ] Add a paramter to the function called size
  - [ ] Test your flag drawing at various sizes to ensure it works

**Comment by nckathleen** [comment]
https://trinket.io/python/333888bb94
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@nckathleen first off, great flag. Here is some food for thought. You organized all of your code into functions. Awesome Job. However you call your functions with other python code in between making it tough to read. An alternate approach would be to write the additional code in the functions themselves so that way the code at the bottom it is easier to read. Does that make sense? By all means you are not wrong it's just a question of "What is easy for me or others to read?" It would look like something below:

function_a()
function_b()
function _c()

**Comment by nckathleen** [comment]
I totally understand, but for the life of me, I can't think of a way to move more to the functions.  I would love to talk about it tomorrow.
