### ISSUE TITLE
02 -- Apple Tree Roots -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#39]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [x] Hard mode (optional)
  - [x] Each time through the loop, print out the number of iterations that have occurred
  - [x] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [x] Nightmare mode (optional)
  - [x] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by JonathanFrederick** [comment]
https://github.com/JonathanFrederick/approximate-square-root

**Comment by JonathanFrederick** [comment]
@jamesmallen @powder-river 
SUBMITTED

**Comment by powder-river** [comment]
@JonathanFrederick I have to nitpick because your code is that awesome! consider in the future when naming to user underscores_ in your case guess_1 and guess_2 just makes things a little more readable. Also as I am sure you are aware there is a sqrt function in the Math library. Food for thought: if you have a function you named sqrt and you import sqrt from math, what happens? Awesome job, keep it up!
